--- # Example-5 Loops in playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: add multiple user
            user: name="{{item}}" state=present
            with_items:
                    - user1
                    - user2
                    - user3
