--- install java and download kafka using variable 
- name: install kafka
  hosts: demo
  become: true
  vars:
          - kafkaURL: https://mirrors.estointernet.in/apache/kafka/2.7.0/kafka-2.7.0-src.tgz
  tasks:
          - name: install java
            yum:
                    name: java
                    state: latest
          - name: download kafka
            get_url:
                    url: "{{ kafkaURL}}"
                    dest: /usr/local
